---
# defaults file for trident-storage-setup

netapp_osv: false

trident_namespace: "trident"

trident_operator_image: "quay.io/mukrishn/trident-operator:v21.01.0"
trident_image: "quay.io/mukrishn/trident:v21.01.0"
trident_autosupport_image: "quay.io/mukrishn/trident-autosupport:v21.01.0"

########################
## VM Input Variables ##
########################

vsim_int_net: "192.167.100.0/24"
vsim_disk_image_dir: "/var/lib/vm_storage"
vsim_snapshot_image_src: "http://perf1.perf.lab.eng.bos.redhat.com/pub/dwilson/OntapGoldImage.tar.gz"

ontap_password: "MTAweWFyZC0K"

###################
## IP Allocation ##
###################

# Baremetal external CIDR
extcidrnet: "192.168.216.0/21"

# Nth IP assigned to Management LIF
lif_ip_nth: 1330

