apiVersion: v1
kind: Namespace
metadata:
  name: ztp-group-du-sno
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-platform-upgrade-prep
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-platform-upgrade
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-operator-upgrade-prep
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-operator-upgrade
