---
# Playbook to install RHACM
#
# Example Usage:
#
# export KUBECONFIG=/home/user/kubeconfig
# time ansible-playbook -i ansible/inventory/hosts ansible/rhacm-hub.yml -e "rhacm_version=2.1"
#

- name: Install released version of RHACM
  hosts: orchestration
  vars_files:
    - vars/all.yml
  pre_tasks:
    - name: run validations
      include_tasks: tasks/validation.yml
  roles:
    - rhacm_hub
