apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: "amq"
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
  kafka:
    config:
      log.message.format.version: "2.5"
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
      message.max.bytes: 10485760
    listeners:
      plain:
        authentiation:
          type: scram-sha-512
      tls:
        authentiation:
          type: tls
    replicas: 3
    NodeSelector:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "{{ kafka_instances.key }}"
          operator: In
          values:
          - "{{ kafka_instances.value }}"
    #affinity:
    #  nodeAffinity:
    #    requiredDuringSchedulingIgnoredDuringExecution:
    #      nodeSeletorTerms:
    #      - matchExpressions:
    #        - key: dedicated
    #          operator: In
    #          values:
    #          - Kafka
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
      class: kafka-local-brokers
    version: 2.5.0
  zookeeper:
    NodeSelector:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "{{ kafka_instances.key }}"
          operator: In
          values:
          - "{{ kafka_instances.value }}"
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
      class: kafka-local-zookeepers

